services:


  # Zookeeper for Kafka and other distributed coordination
  zookeeper:
    image: bitnami/zookeeper:3.9.3 # Recent stable version
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181" # Client port
    environment:
      - ZOO_ENABLE_AUTH=no # For development, disable auth for simplicity
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=10
      - ZOO_SYNC_LIMIT=5
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - hadoop-net

  

volumes:
  zookeeper_data:

networks:
  hadoop-net:
    driver: bridge