services:


  # Zookeeper for Kafka and other distributed coordination
  zookeeper:
    image: bitnami/zookeeper:3.9.3 # Recent stable version
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181" # Client port
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes # For development, disable auth for simplicity
      - ZOO_TICK_TIME=2000
      - ZOO_INIT_LIMIT=10
      - ZOO_SYNC_LIMIT=5
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - hadoop-net
    healthcheck: 
      test: ["CMD", "sh", "-c", "nc -z localhost 2181 || exit 1"] # Check if client port is open
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s # Give Zookeeper time to initialize
  

volumes:
  zookeeper_data:

networks:
  hadoop-net:
    driver: bridge